"""Constants for FortiOS-KD."""

DOMAIN = "fortios_kd"
DATA_FILTER_MANAGER = "filter_manager"

DEFAULT_VERIFY_SSL = True

CONF_ORGANIZATION_MODE = "organization_mode"
ORGANIZATION_MODE_NONE = "none"
ORGANIZATION_MODE_AREA = "area"
ORGANIZATION_MODE_LABEL = "label"
DEFAULT_ORGANIZATION_MODE = ORGANIZATION_MODE_NONE

CONF_HUB_AREA_ID = "hub_area_id"
CONF_NEW_HUB_AREA_NAME = "new_hub_area_name"
CONF_INHERIT_HUB_AREA = "inherit_hub_area"
DEFAULT_INHERIT_HUB_AREA = False
CONF_MOVE_DEVICES_WITH_HUB = "move_devices_if_hub_moves"
DEFAULT_MOVE_DEVICES_WITH_HUB = False
CONF_CLIENTS_FOLLOW_AP_AREA = "clients_follow_ap_area"
DEFAULT_CLIENTS_FOLLOW_AP_AREA = False
CONF_CLIENTS_FOLLOW_AP_LABELS = "clients_follow_ap_labels"
DEFAULT_CLIENTS_FOLLOW_AP_LABELS = False

CONF_HUB_LABEL = "hub_label"
CONF_HUB_LABEL_ID = "hub_label_id"
CONF_NEW_HUB_LABEL_NAME = "new_hub_label_name"
CONF_HUB_LABEL_COLOR = "hub_label_color"
DEFAULT_HUB_LABEL_COLOR = [3, 169, 244]

CONF_REQUEST_TIMEOUT = "request_timeout"
DEFAULT_REQUEST_TIMEOUT = 60

CONF_INCLUDE_UNASSIGNED_SSIDS = "include_unassigned_ssids"
DEFAULT_INCLUDE_UNASSIGNED_SSIDS = False

CONF_MASK_SERIAL_NUMBERS = "mask_serial_numbers"
DEFAULT_MASK_SERIAL_NUMBERS = True
CONF_MASK_SSIDS = "mask_ssids"
DEFAULT_MASK_SSIDS = True
CONF_MASK_CLIENT_MACS = "mask_client_macs"
DEFAULT_MASK_CLIENT_MACS = True

CONF_MASK_CLIENT_HOSTNAMES = "mask_client_hostnames"
DEFAULT_MASK_CLIENT_HOSTNAMES = True

CONF_MASK_VLAN_IDS = "mask_vlan_ids"
DEFAULT_MASK_VLAN_IDS = True

CONF_MASK_AP_NAMES = "mask_ap_names"
DEFAULT_MASK_AP_NAMES = True
